kind: Pipeline
version: v1
name: test-pipeline
services:
  - name: db1
    image: postgres:alpine
    env:
      POSTGRES_PASSWORD:
        from_secret: postgres_pass
    port: 5432
    command: docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200'
steps:    
  - name: skip-build-if-not-master
    when:
      branch:
        - master
        - feature/*
    then: cargo-build
    else: cargo-clippy

  - name: cargo-build
    image: "rust:1"
    command: cargo build

  - name: cargo-clippy
    image: "rust:1"
    command:
      - rustup component add clippy
      - cargo clippy

  - name: cargo-fmt
    image: "rust:1"
    command:
      - rustup component add rustfmt
      - cargo fmt -v
